#!/sbin/sh

set -e

DESTDIR=${DESTDIR:-${BASEDIR:-}}
[ ${DESTDIR} = '/' ] && DESTDIR=
LOCALDIR=/usr/local
[ -n ${LOCALDIR} ] && USERDIR=${LOCALDIR} || USERDIR=/usr

CFGOWN=root
CFGGRP=sys

# /etc/op.conf
test -f ${DESTDIR}${LOCALDIR}/etc/op.conf ||
    cp ${DESTDIR}${LOCALDIR}/etc/op.conf-dist ${DESTDIR}${LOCALDIR}/etc/op.conf
chown ${CFGOWN}:${CFGGRP} ${DESTDIR}${LOCALDIR}/etc/op.conf
chmod 600 ${DESTDIR}${LOCALDIR}/etc/op.conf

# /etc/op.d/*
case ${DESTDIR}${LOCALDIR}/etc/op.d/* in */\*) ;; *)
chown ${CFGOWN}:${CFGGRP} ${DESTDIR}${LOCALDIR}/etc/op.d/* || : set -e
chmod 600 ${DESTDIR}${LOCALDIR}/etc/op.d/* || : set -e
esac

# eof
