#!/usr/bin/sh

pkg=op
ver=1.34.aix52
exc='op.conf$'
dir=build/usr/local
usr=root
grp=system
rdir=/home/ftp/diffusion/exploitation/op
#post='chmod 700 /tmp/${pkg}_${ver}/${dir}/usr/local/etc/op.d'

PATH=/usr/local/bin:$PATH # tar
cd build/usr/local

. ../../../../mkpkg
